// Generated by Xata Codegen 0.27.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "products",
    columns: [
      { name: "platform", type: "string" },
      { name: "productName", type: "string" },
      { name: "price", type: "string" },
      { name: "url", type: "string" },
      { name: "productID", type: "string" },
      { name: "userid", type: "string" },
    ],
  },
  {
    name: "expense",
    columns: [
      { name: "userid", type: "string" },
      { name: "title", type: "string" },
      { name: "category", type: "string" },
      { name: "code", type: "string" },
      { name: "price", type: "string" },
      { name: "date", type: "string" },
    ],
  },
  {
    name: "account",
    columns: [
      { name: "userid", type: "string" },
      { name: "username", type: "string" },
      { name: "card_number", type: "string" },
      { name: "budget", type: "string" },
      { name: "card_name", type: "string" },
      { name: "expiry", type: "string" },
      { name: "cvv", type: "string" },
      { name: "code", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Products = InferredTypes["products"];
export type ProductsRecord = Products & XataRecord;

export type Expense = InferredTypes["expense"];
export type ExpenseRecord = Expense & XataRecord;

export type Account = InferredTypes["account"];
export type AccountRecord = Account & XataRecord;

export type DatabaseSchema = {
  products: ProductsRecord;
  expense: ExpenseRecord;
  account: AccountRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://Timi-s-workspace-eouder.us-east-1.xata.sh/db/expi",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
